;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        TeX-insert-quote
        TeX-insert-sub-or-superscript
        ace-jump-move
        ace-jump-word-mode
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        electric-graphviz-dot-semi
        electric-newline-and-maybe-indent
        haskell-indentation-delete-backward-char
        haskell-indentation-delete-char
        indent-for-tab-command
        indent-new-comment-line
        isearch-abort
        isearch-backward-regexp
        isearch-delete-char
        isearch-forward-regexp
        isearch-printing-char
        kill-region
        org-return-indent
        org-self-insert-command
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-forward-up
        paredit-kill
        paredit-newline
        paredit-open-curly
        paredit-open-round
        paredit-open-square
        paredit-semicolon
        paredit-splice-sexp
        sgml-slash
        shm/del
        shm/kill-region
        shm/open-paren
        shm/raise
        shm/space
        sp--self-insert-command
        sp-backward-delete-char
        sp-delete-char
        sp-forward-slurp-sexp
        sp-kill-hybrid-sexp
        sp-kill-word
        sp-splice-sexp
        suspend-frame
        vr/isearch-forward
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-paren
        cider-eval-defun-at-point
        ido-switch-buffer
        isearch-exit
        isearch-other-control-char
        smex
        ))
